
CREATE DATABASE IF NOT EXISTS plugin_db;
USE plugin_db;
CREATE TABLE IF NOT EXISTS plugins (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL,
    path VARCHAR(500) NOT NULL
);
